version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jade_mysql
    platform: linux/amd64  # Añade esta línea
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "iot_project"
      MYSQL_USER: "jade_user"
      MYSQL_PASSWORD: "jade_password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local